feat: allow custom formatting for status components
nix-community/nixvim pull request #1018
Opened 2024-02-04 23:18 UTC by jakehamilton

Lualine allows you to specify a custom formatter function which can process the final status component string. This can be useful for augmenting existing status components and tweaking the output dynamically.

2024-02-07 13:00 UTC, traxys requested changes

2024-02-07 13:00 UTC, traxys commented on plugins/statuslines/lualine.nix
> +            fmt = helpers.mkNullOrOption helpers.nixvimTypes.rawLua ''
I'd suggest making an option of type `nullOr strLuaFn` and using an `apply` to map it to a raw value, so the user can simply input a string (see other options that use `apply`, many of them do that)

2024-03-06 20:49 UTC, traxys requested changes

2024-03-06 20:49 UTC, traxys commented on tests/test-sources/plugins/statuslines/lualine.nix
> +            fmt.__raw = ''
You need to remove the `__raw`

2024-03-06 23:09 UTC, jakehamilton commented on tests/test-sources/plugins/statuslines/lualine.nix
> +            fmt.__raw = ''
Oh whoops! Thank you for catching this!

2024-03-22 12:09 UTC, traxys approved these changes

2024-03-22 12:09 UTC, merged