fix: add ripgrep for todo-comments functionality
nix-community/nixvim pull request #1020
Opened 2024-02-04 23:35 UTC by jakehamilton

Attempting to use todo-comments without `ripgrep` isn't very useful since the plugin won't be able to find comments in your files based on keywords. This commit adds a new option, defaulting enabled, to add `ripgrep` to the resulting neovim build.

2024-02-05 00:03 UTC, traxys requested changes
There a are a few other places where we have those kind of optional but set by default packages, like gcc for treesitter, and we use a single option, of type null or package, and don't add the package if it's null. Could you do the same here please?

2024-02-05 01:47 UTC, jakehamilton commented
I've updated this PR to match how things are done in the treesitter module. Let me know if there's anything else that should be tweaked :+1:

2024-02-05 09:50 UTC, traxys commented
Could you add a test disabling ripgrep in tests/test-sources/plugins/utils/todo-comments.nix

2024-03-06 20:48 UTC, traxys approved these changes

2024-03-06 20:48 UTC, merged