plugins/julia-cell: switch to mkVimPlugin
nix-community/nixvim pull request #1084
Opened 2024-02-14 07:58 UTC by GaetanLepage

2024-02-19 21:19 UTC, traxys requested changes

2024-02-19 21:19 UTC, traxys commented on plugins/languages/julia/julia-cell.nix
> +      # TODO introduced 2024-02-19: remove 2024-03-19
I'd suggest removal in 2024-04-19

2024-02-19 23:08 UTC, GaetanLepage commented on plugins/languages/julia/julia-cell.nix
> +      # TODO introduced 2024-02-19: remove 2024-03-19
Done !

2024-02-20 09:02 UTC, traxys approved these changes

2024-02-20 09:03 UTC, merged