plugins/undotree: switch to settings-style
nix-community/nixvim pull request #1087
Opened 2024-02-14 09:36 UTC by GaetanLepage

2024-02-19 21:25 UTC, traxys reviewed
I think before removing the options we need a way to link to the plugin homepage, or at the minimum add a `meta.url` option in order to fetch it from the documentation.

2024-02-19 21:25 UTC, traxys commented on plugins/utils/undotree.nix
> +          (basePluginPath ++ ["settings" optionName])
The renamed options won't have the right name I think, they need  to start by an uppercase letter

2024-02-21 20:05 UTC, traxys requested changes

2024-02-21 20:05 UTC, traxys commented on plugins/utils/undotree.nix
> +    # TODO introduced 2024-02-19: remove 2024-03-19
04-19

2024-02-22 00:34 UTC, GaetanLepage commented on plugins/utils/undotree.nix
> +    # TODO introduced 2024-02-19: remove 2024-03-19
Done

2024-02-22 07:25 UTC, traxys approved these changes

2024-02-22 09:12 UTC, merged