plugins/smart-splits: init
nix-community/nixvim pull request #1090
Opened 2024-02-14 11:18 UTC by foo-dogsquared

First stab at making a (formal) NixVim plugin unlike what I'm doing at my own NixVim config. I'm guessing there is a migration at Nix RFC42-style settings so I did that.

Resolves #1050. (Probably a follow-up PR for [legendary.nvim](https://github.com/mrjones2014/legendary.nvim) as it has integration for it. Also, it looks interesting.)

Also, I cannot test this in my local setup as it always crashes so I hope you don't mind if I fully rely on the CI for the testing.

2024-02-15 09:41 UTC, GaetanLepage requested changes
Hello, this looks pretty good.
You can actually simplify the implementation using our brand new `mkNeovimPlugin` helper.
Have a look at [this PR](https://github.com/nix-community/nixvim/pull/971/files#diff-cb75710d2ff4866b9b3c544b2d823265c7e091a86e5db224aa79ac1cd62b0099) for inspiration.

2024-02-28 09:50 UTC, foo-dogsquared commented
Converted into `mkNeovimPlugin` and also rebased it on top of f755eeb961a4d13ec72921cb4dbc4f2d6c8a58bb.

2024-02-28 10:05 UTC, GaetanLepage requested changes
Few nit picks but otherwise looks good !

2024-02-28 10:05 UTC, GaetanLepage commented on plugins/utils/smart-splits.nix
> +  maintainers = with lib.maintainers; [foo-dogsquared];
```suggestion
  name = "smart-splits";
  originalName = "spart-splits.nvim";

  maintainers = with lib.maintainers; [foo-dogsquared];
```

2024-02-28 10:05 UTC, GaetanLepage commented on plugins/utils/smart-splits.nix
> +  maintainers = with lib.maintainers; [foo-dogsquared];
```suggestion
  name = "smart-splits";
  maintainers = [lib.maintainers.foo-dogsquared];
```

2024-02-28 10:05 UTC, GaetanLepage commented on plugins/utils/smart-splits.nix
> +}
```suggestion
  defaultPackage = pkgs.vimPlugins.smart-splits-nvim;

  settingsExample = {
    resize_mode = {
      quit_key = "<ESC>";
      resize_keys = ["h" "j" "k" "l"];
      silent = true;
    };
    ignored_events = ["BufEnter" "WinEnter"];
  };
}
```

2024-02-28 10:10 UTC, foo-dogsquared commented on plugins/utils/smart-splits.nix
> +  maintainers = with lib.maintainers; [foo-dogsquared];
Done.

2024-02-28 10:10 UTC, foo-dogsquared commented on plugins/utils/smart-splits.nix
> +}
Done and done.

2024-02-28 10:13 UTC, foo-dogsquared commented
Also fixed the error in CI. Apparently, I'm not using the helper right.

2024-02-28 11:00 UTC, merged