plugins/crates-nvim: init
nix-community/nixvim pull request #1165
Opened 2024-02-27 16:29 UTC by alisonjenkins

Adds crates-nvim as a plugin instead of just a completion source for cmp.

Resolves: https://github.com/nix-community/nixvim/issues/1149

2024-02-27 17:15 UTC, traxys requested changes
Because it can be a cmp source in addition of a plugin could you add a test enabling the plugin in cmp too?

2024-08-08 13:22 UTC, Eveeifyeve commented
This PR Is a copy of #1205

2024-09-07 02:32 UTC, Eveeifyeve commented
> Because it can be a cmp source in addition of a plugin could you add a test enabling the plugin in cmp too?

A PR has been made for this [here](1205)

2024-09-08 22:16 UTC, GaetanLepage commented
FWIW I had opened a PR a while back: https://github.com/nix-community/nixvim/pull/1205

2024-09-16 20:55 UTC, closed without merging