plugins/crates: init
nix-community/nixvim pull request #1205
Opened 2024-03-04 18:44 UTC by GaetanLepage

Add support for [crates.nvim](https://github.com/Saecki/crates.nvim/tree/main).

I am not convinced on whether I should explicitly declare some options or none...

Fixes #1149

2024-03-06 21:08 UTC, traxys reviewed
The wiki seems to put forwards:
- the `lsp` options
- the `nvim-cmp` completion source (it seems we need to do more that add it to `sources for that!)
- the `coq.nvim`  completion  source
- The null-ls source

So I'd suggest only adding those.
https://github.com/Saecki/crates.nvim/wiki/Documentation-unstable

2024-03-06 21:08 UTC, traxys commented on plugins/languages/rust/crates.nix
> +      on_attach = helpers.defaultNullOpts.mkLuaFn "function(bufnr) end" ''
Shouldn't we default this to the __lspOnAttach function? I think we should expose this in the helpers in some way, to help  people reuse the default function when creating their own on attach

2024-03-12 19:10 UTC, traxys requested changes

2024-03-12 19:10 UTC, traxys commented on plugins/languages/rust/crates.nix
> +        # '';
This should not be present (And like mentionned we should do something about setting the lsp default value to __lspOnAttach to benefit from the other options, like format.nvim, or LSP specific mappings that we could introduce to solve  #1219))

2024-09-16 21:29 UTC, GaetanLepage commented
@khaneliman if you happen to want to pick this up, go on :)

2024-09-17 12:51 UTC, Eveeifyeve commented
I could look at making changes to this pr as there is two version of crates both cmp and non cmp.

2024-09-17 13:05 UTC, khaneliman commented
> I could look at making changes to this pr as there is two version of crates both cmp and non cmp, to help out if needed.

Feel free if you're interested. I can jump in if needed,

2024-09-27 14:57 UTC, Eveeifyeve commented
Is there any way of good testing?

2024-09-28 08:23 UTC, MattSturgeon commented
> Is there any way of good testing?

You can use `nix flake lock --override-input` in order to temporarily update a nixvim config's flake.lock to use a different input url.

For example:
```bash
# From a nixvim _config_ repo


# Use a local repo
nix flake lock --override-input nixvim ../nixvim-fork

# Use a PR branch
nix flake lock --override-input nixvim github:GaetanLepage/nixvim/crates

# Undo override
git restore flake.lock
```

You can also run nixvim's tests using the `tests` command while in a nixvim devshell:
```bash
# From a nixvim repo


# Enter devshell
nix develop

# Run tests for this plugin (interactive filter)
tests -i
> crates
```

2024-12-05 01:17 UTC, Eveeifyeve commented
I will resolve the conflict and everything on this weekend.

2024-12-19 00:58 UTC, MattSturgeon commented
I'm going to close this for now. We have [`plugins.crates`](https://nix-community.github.io/nixvim/plugins/crates/index.html?highlight=crates#crates) since #2717, and this PR is so old the conflicts will be a nightmare.

If there's anything of value still in this PR, then new PRs can be created to improve or expand the `plugins.crates` module.

2024-12-19 00:58 UTC, closed without merging