treewide: fix typos
nix-community/nixvim pull request #1217
Opened 2024-03-06 16:17 UTC by loicreynier

Found a few typos so I ran `typos` to fix them. Most of the typos were in option descriptions. Checks passed.

Also added a pre-commit hook for it in the devshell. Let me know if we should keep this hook or only merge the typo fixes.

2024-03-06 20:41 UTC, traxys requested changes

2024-03-06 20:41 UTC, traxys commented on plugins/utils/neogen.nix
> +      placeholderHighlight = helpers.defaultNullOpts.mkStr "DiagnosticHint" ''
We  need to introduce a warning that this option was renamed, even if it was a  typo :/ See how other renames are done

2024-03-06 20:41 UTC, traxys commented on plugins/utils/vim-matchup.nix
> +      deferred = {
You need to rename both sub options  in  this case

2024-03-07 09:40 UTC, loicreynier commented
Just added renames using `mkRenamedOptionModule`. It is what you intended? Haven't go the time to rebase into `main` yet.

2024-03-07 10:02 UTC, traxys commented
Yes exactly!

2024-03-07 14:47 UTC, loicreynier commented
Rebased into `main`.

2024-03-07 18:43 UTC, traxys approved these changes

2024-03-07 18:44 UTC, merged