plugins/vscode: init
nix-community/nixvim pull request #1263
Opened 2024-03-13 22:07 UTC by loicreynier

Add  [`vscode.nvim`](https://github.com/Mofiqul/vscode.nvim) colorscheme.

2024-03-13 23:21 UTC, traxys requested changes

2024-03-13 23:21 UTC, traxys commented on plugins/colorschemes/vscode.nix
> +        local vscode = require("vscode")
maybe `_vscode` in case an user defines a variable of the same name?

2024-03-13 23:21 UTC, traxys commented on plugins/colorschemes/vscode.nix
> +        (with helpers.nixvimTypes; attrsOf strLua)
Shouldn't this be attrsOf anything? From the readme is seems you can do `'#FFFFFF'`. strLua is mean for rawLuaCode.

I think the option should be a defaultNullOpts.mkAttrsOf types.str if I unsterstand the readme.

2024-03-13 23:21 UTC, traxys commented on plugins/colorschemes/vscode.nix
> +        (with helpers.nixvimTypes; attrsOf highlight)
I think this should be a defaultNullOpts.mkAttrsOf nixvimTypes.highlight

2024-03-14 11:07 UTC, loicreynier commented
Thanks for the review! I implemented and tested your suggestions.

2024-03-14 13:55 UTC, merged