plugins/codeium-vim: fix keymaps
nix-community/nixvim pull request #1298
Opened 2024-03-21 13:18 UTC by GaetanLepage

Fixes #1156

2024-03-21 14:04 UTC, GaetanLepage commented
This patch fixes the error described in the linked issue.
However, I can't make the `accept` keybind works... Seems related to https://github.com/Exafunction/codeium.vim/issues/215.

2024-03-22 09:26 UTC, GaetanLepage commented
@hyperpuncher @spl3g could you test this fix please ?
It is working better than the current solution, but I am curious to see if `accept` will work for you.

2024-03-22 12:05 UTC, traxys requested changes

2024-03-22 12:05 UTC, traxys commented on plugins/completion/codeium-vim.nix
> +            action.__raw = let
I'd prefer we use `helpers.mkRaw`, it is a bit more descriptive

2024-03-22 14:09 UTC, traxys approved these changes

2024-03-22 14:10 UTC, merged