plugins/sandwich: init
nix-community/nixvim pull request #1326
Opened 2024-03-26 16:27 UTC by GaetanLepage

Add support for [vim-sandwich](https://github.com/machakann/vim-sandwich).

Fixes #1161

2024-03-27 14:06 UTC, traxys requested changes
I don't think this is a nice way to package the plugin, because most of the actual configuration options use the `#` syntax.

I think this plugin does not fit very nicely in the raw "settings" model, we may need to do some manual work for it

2024-03-28 08:42 UTC, GaetanLepage commented
> I don't think this is a nice way to package the plugin, because most of the actual configuration options use the `#` syntax.
> 
> I think this plugin does not fit very nicely in the raw "settings" model, we may need to do some manual work for it

I see your point. However, there is no perfect solution for this plugin. I would like to avoid our previous model of crafting custom options to wrap the plugin ones.
I would argue that the user of this plugin will be very unlikely to customize the behavior to the point of needing those `#` settings. This is backed up by a research across publicly available neovim configurations on GitHub.

Also, I have added a notice in the plugin description.
My opinion would be to ship this module as is.

2024-03-28 10:33 UTC, traxys commented
> This is backed up by a search across publicly available neovim configurations on GitHub.

Good enough for me

2024-03-28 10:33 UTC, traxys approved these changes

2024-03-28 11:57 UTC, merged