flake: disable `allow-import-from-derivation`
nix-community/nixvim pull request #1827
Opened 2024-07-07 00:51 UTC by MattSturgeon

Unfortunately this will print a confirmation when first using the flake:

```
do you want to allow configuration setting 'allow-import-from-derivation' to be set to 'false' (y/N)?
```

This is no different to the cachix configs though.

2024-07-07 01:18 UTC, MattSturgeon commented
Looks like a number of tests rely on IFD.

If we can find a way to do them without IFD, I think we should.

I think some of the packages used by the update CI are being included in `checks`? We probably _don't_ want that?

2024-07-07 08:44 UTC, traxys commented
Yeah I agree we probably don't want that, we may need to move them to a different section than packages

2024-07-08 06:42 UTC, GaetanLepage requested changes
- What do you mean by "the first time using the flake" ? The first time running `nix run` with the nixvim flake as an input of your flake ?
- `nocheckPackages` -> `noCheckPackages` ?

2024-07-08 07:07 UTC, MattSturgeon commented
> * What do you mean by "the first time using the flake" ? The first time running `nix run` with the nixvim flake as an input of your flake ?

The first time running any `nix` command with this flake checked out locally.

I don't _think_ our flake's nixConfig is inherited by downstream flakes (haven't tested, could be wrong).

>     * `nocheckPackages` -> `noCheckPackages` ?

Sure, no strong opinion.

---

Just for the record, this PR doesn't currently do what it intends to. Passing the `--allow-import-from-derivation` flag to `nix` commands _does not_ override the flake's nix config, so the update CI will not work if we merge this in its current state.

2024-07-11 00:36 UTC, MattSturgeon commented
Maybe we can configure nix in GitHub CI to not allow the flake to set nixConfig?

2024-08-03 22:28 UTC, MattSturgeon commented
Since #1980, we're now able to disable IFD in the flake. I've therefore rebased this and removed the outdated implementation.

Just need to fix/remove some of the new tests added by https://github.com/nix-community/nixvim/commit/299d0406bb339283969907d1f171f0eec7d84c43

Tests that need to read the content of files will have to be custom test derivations so that we can read the files during the build/check phase rather than importing the file into the eval.

2024-08-04 07:30 UTC, GaetanLepage approved these changes
Ok let's go !

2024-08-04 09:03 UTC, MattSturgeon commented
@mergifyio queue

2024-08-04 09:03 UTC, merged