plugins/nvim-snippets: init
nix-community/nixvim pull request #1979
Opened 2024-08-03 16:52 UTC by psfloyd

Adds support for [nvim-snippets](https://github.com/garymjr/nvim-snippets).

2024-08-03 21:06 UTC, GaetanLepage approved these changes
Thanks for this contribution.
Your PR looks promising !

I made a few minor remarks.

2024-08-03 21:06 UTC, GaetanLepage commented on tests/test-sources/plugins/snippets/nvim-snippets.nix
> +          function()
```suggestion
        action.__raw ''
          function()
```

2024-08-03 21:06 UTC, GaetanLepage commented on plugins/snippets/nvim-snippets.nix
> +    create_autocmd = helpers.defaultNullOpts.mkBool false "Optionally load all snippets when opening a file. Only needed if not using nvim-cmp.";
```suggestion
    create_autocmd = helpers.defaultNullOpts.mkBool false ''
      Optionally load all snippets when opening a file.
      Only needed if not using nvim-cmp.
    '';

```

Please, adopt the same coding style as the rest of the code base. This ensure consistency across the project.

2024-08-03 21:07 UTC, GaetanLepage requested changes
mistake.

2024-08-03 21:37 UTC, GaetanLepage requested changes
A bit more nit-picking...

2024-08-03 21:37 UTC, GaetanLepage commented on tests/test-sources/plugins/snippets/nvim-snippets.nix
> +          search_paths = [ { __raw = "vim.fn.stdpath('config') .. '/snippets'"; } ];
```suggestion
    plugins = {
      friendly-snippets.enable = true;

      cmp = {
        enable = true;

        settings = {
          sources = [ { name = "snippets"; } ];
          mapping.__raw = "require('cmp').mapping.preset.insert()";
        };
      };
      nvim-snippets = {
        enable = true;
        settings = {
          create_autocmd = true;
          create_cmp_source = true;
          friendly_snippets = true;
          ignored_filetypes = [ "lua" ];
          extended_filetypes = {
            typescript = [ "javascript" ];
          };
          global_snippets = [ "all" ];
          search_paths = [ { __raw = "vim.fn.stdpath('config') .. '/snippets'"; } ];
```

2024-08-03 21:37 UTC, GaetanLepage commented on tests/test-sources/plugins/snippets/nvim-snippets.nix
> +  settings = {
Usually we have an `defaults` test case that strictly copies the upstream defaults and eventually an `example` test case where we set non-defaults value.

2024-08-03 21:37 UTC, GaetanLepage commented on plugins/snippets/nvim-snippets.nix
> +    create_cmp_source = helpers.defaultNullOpts.mkBool true ''
```suggestion
    '';

    create_cmp_source = helpers.defaultNullOpts.mkBool true ''
```

Please, add a line break between each option declaration.

2024-08-03 21:37 UTC, GaetanLepage commented on plugins/snippets/nvim-snippets.nix
> +helpers.neovim-plugin.mkNeovimPlugin config {
```suggestion
}:
let
  inherit (lib) types;
  inherit (lib.nixvim) defaultNullOpts;
in
helpers.neovim-plugin.mkNeovimPlugin config {
```

This is a brand-new coding style that we are trying out.

2024-08-06 06:23 UTC, GaetanLepage requested changes
This looks good to me !
@nix-community/nixvim could you please double-check quickly ?

@psfloyd, please squash your commits so as to have two left:
- `maintainers: add psfloyd`
- `plugins/nvim-snippets: init`

2024-08-06 11:36 UTC, MattSturgeon reviewed
One nit, otherwise LGTM once other feedback is addressed!

2024-08-06 11:36 UTC, MattSturgeon commented on plugins/snippets/nvim-snippets.nix
> +
```suggestion
```

2024-08-07 02:06 UTC, psfloyd commented
It's ready to merge from my part. Squashed the commits and fixed the unnedded newline.

2024-08-07 02:12 UTC, MattSturgeon approved these changes
LGTM, thanks!

2024-08-07 10:25 UTC, GaetanLepage approved these changes
Well done, thanks !

2024-08-07 10:25 UTC, GaetanLepage commented
@mergifyio queue

2024-08-07 10:25 UTC, merged