plugins/lsp: add svelte language server
nix-community/nixvim pull request #498
Opened 2023-08-07 07:46 UTC by GaetanLepage

Add support for the [svelte language server](https://github.com/sveltejs/language-tools/tree/master/packages/language-server).

Fixes #497 

@rupurt, if you have the possibility to test it on your setup, it would be great !

2023-08-07 20:08 UTC, rupurt commented
Looks good on my machine :pray:

2023-08-13 22:08 UTC, traxys requested changes

2023-08-13 22:08 UTC, traxys commented on plugins/lsp/language-servers/svelte.nix
> +              Enable completions for TypeScript.
completions for CSS

2023-08-13 22:08 UTC, traxys commented on plugins/lsp/language-servers/svelte.nix
> +            compilerWarnings = helpers.mkNullOrOption (with types; attrsOf str) ''
compilerwarnings is not in diagnostics

2023-08-13 22:22 UTC, traxys approved these changes

2023-08-13 22:22 UTC, merged

2023-08-14 02:28 UTC, rupurt commented
FWIW, working great on main. That's again y'all!