fix(bufferline): add missing highlight groups for tab separator
nix-community/nixvim pull request #582
Opened 2023-09-09 23:37 UTC by jakehamilton

This commit enables customization of the `tab_separator` and `tab_separator_selected` options for Bufferline. These allow for styling the tab entries that appear on the end of the bufferline.

fixes #581

2023-09-10 00:20 UTC, jakehamilton commented
It looks like there were more groups missing, I've gone ahead and added all of them here 👍

2023-09-10 09:21 UTC, GaetanLepage approved these changes
Thanks for that !

2023-09-10 09:25 UTC, GaetanLepage commented
Could you please rebase your branch from master and then squash your changes in a single commit please ?

2023-09-10 10:35 UTC, jakehamilton commented
@GaetanLepage can do! I have a few more changes coming for other modules as I work on porting things. I'll revisit the PRs and try to break things apart.

2023-09-10 10:43 UTC, GaetanLepage requested changes
Ok ! I will mark it as "changes requested" then.

2023-09-11 10:21 UTC, closed without merging

2023-09-11 10:21 UTC, jakehamilton commented
I have quite a few more changes and I'm going to break them apart and draft new PRs. Sorry for the churn!