docs: add user guide pages
nix-community/nixvim pull request #608
Opened 2023-09-28 08:10 UTC by Wolbyte

This pull request aims to add a new `User Guide` section with pages covering the basics of nixvim installation and usage, as well as some FAQs and tips.

@GaetanLepage is the one helping to document those topics.

2023-12-28 16:04 UTC, trueNAHO approved these changes

2023-12-28 16:04 UTC, trueNAHO requested changes

2023-12-28 16:04 UTC, trueNAHO commented on docs/pages/FAQ.md
> +### _The option `home` does not exist
```suggestion
### The option `home` does not exist
```

2023-12-30 14:14 UTC, GaetanLepage commented on docs/pages/FAQ.md
> +### _The option `home` does not exist
Thanks !

2024-03-12 23:27 UTC, MattSturgeon commented
I believe this was superseded by #1121 and can be closed?

2024-03-12 23:29 UTC, traxys commented
I think yes

2024-03-12 23:29 UTC, closed without merging