plugins/indent-blankline: update options
nix-community/nixvim pull request #650
Opened 2023-10-17 08:12 UTC by GaetanLepage

2023-10-17 08:30 UTC, GaetanLepage commented
We need to wait for #https://github.com/NixOS/nixpkgs/pull/261262 to land in `nixos-unstable`.
Indeed, these changes expect the latest version of `indent-blankline.nvim`.

2023-10-23 08:49 UTC, traxys requested changes

2023-10-23 08:54 UTC, traxys commented
You forgot to update the test

2023-10-23 09:03 UTC, traxys approved these changes

2023-10-23 09:08 UTC, merged