plugins/fzf-lua: init + test
nix-community/nixvim pull request #793
Opened 2023-12-08 04:01 UTC by budimanjojo

2023-12-08 04:06 UTC, budimanjojo commented
I don't know why the test fails, I tested locally without my addition and it fails too.

2023-12-08 08:36 UTC, GaetanLepage commented on plugins/utils/fzf-lua.nix
> +        type = with types; oneOf [(enum ["default" "fzf-native" "fzf-tmux" "fzf-vim" "max-perf" "telescope" "skim"])];
```suggestion
        type = types.enum ["default" "fzf-native" "fzf-tmux" "fzf-vim" "max-perf" "telescope" "skim"];
```
You don't need `oneOf` here.

2023-12-08 09:35 UTC, budimanjojo commented
@GaetanLepage Done!

2023-12-13 08:14 UTC, budimanjojo commented
@GaetanLepage is there any other issue that I need to fix?

2023-12-13 08:22 UTC, GaetanLepage commented
Hey, sorry for taking so long.
Everything looks nice for now. However, I would encourage you to wrap the plugin options like we do for the other plugins.

The simpler way would be to limit the scope to the ["global options"](https://github.com/ibhagwan/fzf-lua#default-options) that would end up in the `setupOptions` attrs.

If you want to go a bit further, you could create a `keymaps` option that allows the user to create mappings easily (like we do for telescope or harpoon for instance).
You could even add options for the keymaps to be configurable.

I suggest to limit the scope of this PR to the default options though.

2023-12-13 08:34 UTC, budimanjojo commented
Thanks! I'll try to add `keymaps` and `keymapsSilent` option for now. I don't think I understand the "wrap the plugin options like we do for the other plugins" part. Do u mean I need to add more options instead of making users to use `extraOptions` for everything else?

2023-12-13 09:29 UTC, GaetanLepage commented
> Do u mean I need to add more options instead of making users to use `extraOptions` for everything else?

Yes exactly. It is a bit of a pain to do, but it is one of the added value of nixvim ;)

2023-12-14 17:47 UTC, budimanjojo commented
@GaetanLepage I added `keymaps` options. I don't know if my nix knowledge is good enough to create all those setup options without making the code looks messy. Maybe it's just me but I think people should just be good with changing the provided `profile` (or theme) and set those options per keymap like I provided in the example.

Maybe you can accept this PR and maybe if somebody else want to improve this plugin then he/she/they can make another PR?

2023-12-14 17:56 UTC, budimanjojo commented
I also agree that having the setup options added in can be some kind of type checking at build time in case the user provided a wrong options it will fail to build resulting in the user can fix that up before having a broken neovim config. But I'm just not good enough to make it robust. I think the better way to go is to have all the available options in a variable that can also be used for the `actionOpts` in the `keymaps` in my last commit.

But, there are a lot of options that are action name specific, i.e `cwd` is only available in `files` action and this makes my brain hurts just by thinking about it :sweat_smile:

2023-12-20 23:07 UTC, GaetanLepage requested changes
I think that what you have done until now is good.

I would still want to package the options.
If you allow me to do so, I can complete this work by force-pushing to your branch.
Does that sound good to you ?

2023-12-20 23:07 UTC, GaetanLepage commented on plugins/utils/fzf-lua.nix
> +        __unkeyedProfile = cfg.profile;
```suggestion
        __unkeyed_profile = cfg.profile;
```

2023-12-20 23:07 UTC, GaetanLepage commented on plugins/utils/fzf-lua.nix
> +        cfg.keymaps;
```suggestion
          key: action: let
            actionStr =
              if isString action
              then "${action}()"
              else "${action.action}(${helpers.toLuaObject action.actionOpts})";
            actionProps =
              if isString action
              then {}
              else filterAttrs (n: v: n != "action" && n != "actionOpts") action;
          in {
            mode = "n";
            inherit key;
            action = "function() require('fzf-lua').${actionStr} end";
            lua = true;

            options =
              {
                silent = cfg.keymapsSilent;
              }
              // actionProps;
          }
        )
        cfg.keymaps;
```

Maybe, we can remove the `keymapsSilent` option as the user can set `actionProps.silent = true`.

2023-12-20 23:07 UTC, GaetanLepage commented on plugins/utils/fzf-lua.nix
> +      };
This should be made optional (i.e. `helpers.defaultNullOpts.mkEnumFirstDefault`).
We will then only call the `setup` if the user has explicitly provided a profile and/or options.

2023-12-21 04:21 UTC, budimanjojo commented
@GaetanLepage I have commited the requested changes. Yes feel free to push to the branch! Thank you!

2024-02-14 21:49 UTC, GaetanLepage commented
This is finally ready ! Sorry @budimanjojo for taking that long...

2024-02-14 22:45 UTC, traxys approved these changes

2024-02-14 22:46 UTC, GaetanLepage approved these changes

2024-02-14 22:46 UTC, merged

2024-02-15 04:29 UTC, budimanjojo commented
Thank you!