plugin/nvim-lightbulb: update module to match latest breaking changes
nix-community/nixvim pull request #844
Opened 2023-12-24 14:25 UTC by rsHalford

Closes #843.

Could someone please double check line 40 (actionKinds)? As I'm not exactly sure how to get to a `nil` value in lua from nix.

2023-12-24 14:29 UTC, GaetanLepage requested changes
From a first glance, this looks nice.
If some options are removed/renamed in the process, please use `mkRemovedOptionModule` and `mkRenamedOptionModule` to properly warn the users.
You will be able to find some examples using those in the repo. ([here](https://github.com/nix-community/nixvim/blob/310f1ad5b5e7da20832b216a64f6da528331db4a/plugins/filetrees/neo-tree.nix#L12-L23) for instance).

2023-12-24 16:15 UTC, rsHalford commented
Is there a suggested way to create a notice for `plugins.nvim-lightbulb.ignore` (list of strings) now being `plugins.nvim-lightbulb.ignore.clients`?
`mkRenamedOptionModule` doesn't seem like a good fit and I can't seem to find an alternative within [modules.nix](https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix).

(I'm most likely wrong and just haven't seen it)

2023-12-24 16:34 UTC, GaetanLepage commented
> Is there a suggested way to create a notice for `plugins.nvim-lightbulb.ignore` (list of strings) now being `plugins.nvim-lightbulb.ignore.clients`? `mkRenamedOptionModule` doesn't seem like a good fit and I can't seem to find an alternative within [modules.nix](https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix).
> 
> (I'm most likely wrong and just haven't seen it)

You are right, in this case, there is not much we can do.
Let's just not add a warning for this one.

2023-12-29 10:04 UTC, GaetanLepage commented on plugins/lsp/nvim-lightbulb.nix
> +  ];
```suggestion
  imports = let
    basePluginPath = ["plugins" "nvim-lightbulb"];
  in [
    (
      mkRenamedOptionModule
      (basePluginPath ++ ["sign" "priority"])
      (basePluginPath ++ ["priority"])
    )
  ];
```

2023-12-31 19:08 UTC, rsHalford commented on plugins/lsp/nvim-lightbulb.nix
> +  ];
Thanks for pointing that out for me!

2024-02-15 12:42 UTC, GaetanLepage approved these changes

2024-02-15 13:27 UTC, traxys approved these changes

2024-02-15 13:29 UTC, merged